# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160323_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AlterField(
            model_name='eventrepetition',
            name='start_day',
            field=models.DateField(),
        ),
    ]
