# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160329_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='eventrepetition',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='eventrepetition',
            name='repetition',
        ),
        migrations.RemoveField(
            model_name='eventrepetition',
            name='start_day',
        ),
        migrations.AddField(
            model_name='eventrepetition',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='eventrepetition',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
