# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='time',
            field=models.DurationField(),
        ),
    ]
